version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - submodules-{{ .Revision }}
            - submodules-
      - save_cache:
          paths:
            - ./opt
          key: submodules-{{ .Revision }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - store_artifacts:
          path: test-reports
          destination: test-reports
  lint:
    docker:
      - image: circleci/python:3.6.9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - submodules-{{ .Revision }}
            - submodules-
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            flake8
  test:
    docker:
      - image: circleci/python:3.6.9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - submodules-{{ .Revision }}
            - submodules-
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test

workflows:
  version: 2
  build_lint_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build